apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: {{ .Values.ingress.name }}
  namespace: {{ .Valuies.ingress.namespace }}
spec:
- host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
        path: {{ .Values.ingrss.path }}